### ISSUE TITLE
Scraping multiple accounts together

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-ynab-updater#28]
Hello @eshaham. As a nYnaber for a year and a half I was using Finanda import module to scrape all the sites. As they decided to end the life of their desktop product I was looking for alternatives and found your two awesome repositories.

After playing with this library I think adding the following will contribute to its' daily flow:
1. extend `npm run credentials` to manage multiple account together (allowing the user to view list of configured accounts, modify/delete existing, add new ones) and name them as you wish, ie 'home accounts' or 'work accounts'
2. scrape a group of accounts and export a joined csv file to be easily import them together to nYnab.
3. change the layout of the exported csv to match the fields recommended by nYnab: account, date, payee, inflow, outflow, memo.

I think having supporting multiple accounts will reduce the number of key strokes significantly.

I would appreciate your insights :)

**Comment by eshaham** [comment]
@esakal 

> 1. extend npm run credentials to manage multiple account together (allowing the user to view list of configured accounts, modify/delete existing, add new ones) and name them as you wish, ie 'home accounts' or 'work accounts'

sounds good 😄 
> 2. scrape a group of accounts and export a joined csv file to be easily import them together to nYnab.

also sounds good, as long as there's still an option to separate into different files (to keep compatibility with old YNAB)

> 3. change the layout of the exported csv to match the fields recommended by nYnab: account, date, payee, inflow, outflow, memo.

👍

**Comment by esakal** [comment]
I'm starting to work in this feature. If anyone else want to participate or to add his insights feel free to comment.
