### ISSUE TITLE
export multiple account together

### ISSUE THREAD

**Issue by dudutwizer** [eshaham/israeli-ynab-updater#41]
(node:65127) UnhandledPromiseRejectionWarning: TypeError: (0 , _json2csv2.default) is not a function
    at generateSingleReport (/bank-scrapers/israeli-ynab-updater/src/scrape/generate-reports.js:123:23)
    at exports.default (/bank-scrapers/israeli-ynab-updater/src/scrape/scrape-task.js:92:13)
(node:65127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:65127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by dudutwizer** [comment]
found fix

add 
const json2csv = require('json2csv').parse;

**Comment by eshaham** [comment]
@dudutwizer thanks for reporting, fixed
