### ISSUE TITLE
Export all details to CSV

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-ynab-updater#46]
This repository aimed for YNAB format, but as far as I can see, he generally creates a `csv` with only some of the details.

This repository provides very convenient CLI, and it is a pity not to use it as the primary CLI.

So I suggest that there be an option, some flag, that allows exporting all transactions as they are, to `csv`.

**Comment by eshaham** [comment]
@baruchiro that is correct, it is specifically shooting for YNAB users, and it makes no sense exporting more fields. You are more than welcome to create another repo with generic export to CSV - I will add it to the list of known projects under [Israeli Bank Scrapers](https://github.com/eshaham/israeli-bank-scrapers) readme

**Comment by baruchiro** [comment]
The thing is, you have written a very nice CLI here, which also contains the YNAB format.
If I had to choose, I would say that the CLI is an integral part of the `scrapers`, and the YNAB format is extra.
That is, what I propose is that the current repository (YNAB) will be the official interface of the `scrapers`, and perhaps the formats will be a [strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern).
